import VJO.OptimalSearch

/-!
# VJO: Certified Safety Radius

Defines the safety radius σ(M, p, D) and proves key properties.
Analogous to certified radius in randomized smoothing (Cohen et al. ICML 2019).

The safety radius is the supremum of response probabilities among all jailbreak responses,
representing the highest probability at which a jailbreak can occur. If no jailbreak exists,
the safety radius is 0.

## Main Results

1. **Monotonicity**: The jailbreak oracle problem is monotone in ε
2. **UNSAT Certification**: UNSAT result certifies safety bounds
3. **Decoding Strategy Reachability**: More restrictive strategies have fewer reachable responses
4. **Binary Search Correctness**: Binary search converges to safety radius bounds
-/

open BigOperators Finset

/-! ## Definition: Safety Radius -/

/-- The **safety radius** σ(M, p, D, n_max) is the supremum of response probabilities
    among all jailbreak responses of length ≤ n_max.

    If no jailbreak response exists, sSup ∅ = 0 by Mathlib convention.
    This represents the highest probability at which a jailbreak can occur. -/
noncomputable def safetyRadius {V : Type*} [Fintype V] [DecidableEq V]
    (M : Model V) (D : DecodingStrategy V) (p : Prompt V) (n_max : ℕ) : ℝ :=
  sSup (responseProb M D p '' {r : Response V | r.length ≤ n_max ∧ Judge p r = true})

/-! ## Theorem 1: Monotonicity -/

/-- **Theorem 1 (Monotonicity)**: The jailbreak oracle problem is monotone in ε.
    If no jailbreak exists at threshold ε₀, then no jailbreak exists at any
    higher threshold ε₁ ≥ ε₀.

    This follows because the jailbreak threshold scales linearly with ε:
    a higher ε means a higher bar to clear. -/
theorem jailbreakOracleProblem_monotone {V : Type*} [Fintype V] [DecidableEq V]
    (M : Model V) (p : Prompt V) (D : DecodingStrategy V)
    (ε₀ ε₁ : ℝ) (hε : 0 ≤ ε₀) (hle : ε₀ ≤ ε₁)
    (hunsat : ¬jailbreakOracleProblem M p D ε₀) :
    ¬jailbreakOracleProblem M p D ε₁ := by
  intro ⟨r, hprob, hjudge⟩
  apply hunsat
  refine ⟨r, ?_, hjudge⟩
  unfold jailbreakThreshold at hprob ⊢
  have hLnonneg := nTokenLikelihood_nonneg M p D r.length
  calc responseProb M D p r
      ≥ ε₁ * nTokenLikelihood M p D r.length := hprob
    _ ≥ ε₀ * nTokenLikelihood M p D r.length := by nlinarith

/-! ## Theorem 2: UNSAT Certification -/

/-- **Theorem 2 (UNSAT implies safety bound)**: If the VJO search returns UNSAT
    at parameter ε (meaning no jailbreak with probability ≥ ε·L_n exists),
    then every response of length ≤ n_max either:
    - has probability < jailbreakThreshold at ε, or
    - is not judged as a jailbreak.

    This certifies that the safety radius is bounded by the UNSAT threshold. -/
theorem unsat_implies_safety_bound {V : Type*} [Fintype V] [DecidableEq V]
    (M : Model V) (p : Prompt V) (D : DecodingStrategy V) (ε : ℝ)
    (n_max : ℕ)
    (hunsat : ¬jailbreakOracleProblem M p D ε) :
    ∀ r : Response V,
      r.length ≤ n_max →
      responseProb M D p r < jailbreakThreshold M p D ε r.length ∨
      Judge p r = false := by
  intro r _
  by_contra h
  push_neg at h
  apply hunsat
  have hjudge : Judge p r = true := by
    cases hj : Judge p r
    · exact (h.2 hj).elim
    · rfl
  exact ⟨r, h.1, hjudge⟩

/-- **Corollary**: If UNSAT at ε, then the safety radius is bounded.
    
    More precisely: any jailbreak response has probability strictly less than
    the UNSAT threshold. -/
theorem unsat_bounds_safetyRadius {V : Type*} [Fintype V] [DecidableEq V]
    (M : Model V) (p : Prompt V) (D : DecodingStrategy V) (ε : ℝ)
    (n_max : ℕ) (hε : 0 < ε)
    (hunsat : ¬jailbreakOracleProblem M p D ε) :
    ∀ r : Response V,
      r.length ≤ n_max →
      Judge p r = true →
      responseProb M D p r < jailbreakThreshold M p D ε r.length := by
  intro r hlen hjudge
  have := unsat_implies_safety_bound M p D ε n_max hunsat r hlen
  rcases this with h | h
  · exact h
  · simp [hjudge] at h

/-! ## Theorem 3: Decoding Strategy Reachability -/

/-- A response is **reachable** under decoding strategy D if every token
    in the response is eligible at the corresponding position.
    
    Intuitively: the response could actually be generated by the strategy. -/
def isReachable {V : Type*} [Fintype V] [DecidableEq V]
    (M : Model V) (D : DecodingStrategy V) (p : Prompt V) (r : Response V) : Prop :=
  ∀ i : Fin r.length, r.get i ∈ D.eligible M p (r.take i.val)

/-- A decoding strategy D₁ is **more restrictive** than D₂ if its eligible
    set is always a subset of D₂'s eligible set. -/
def isMoreRestrictive {V : Type*} [Fintype V] [DecidableEq V]
    (D₁ D₂ : DecodingStrategy V) (M : Model V) : Prop :=
  ∀ p pfx, D₁.eligible M p pfx ⊆ D₂.eligible M p pfx

/-- **Theorem 3a (Reachability monotonicity)**: If D₁ is more restrictive than D₂,
    then any response reachable under D₁ is also reachable under D₂.
    
    More restrictive decoding strategies can only decrease the set of reachable
    responses, not increase it. -/
theorem reachability_monotone {V : Type*} [Fintype V] [DecidableEq V]
    (M : Model V) (D₁ D₂ : DecodingStrategy V) (p : Prompt V)
    (hmore : isMoreRestrictive D₁ D₂ M)
    (r : Response V) (hreach : isReachable M D₁ p r) :
    isReachable M D₂ p r := by
  intro i
  exact hmore p (r.take i.val) (hreach i)

/-- **Theorem 3b (Jailbreak set containment)**: If D₁ is more restrictive than D₂,
    then the set of reachable jailbreak responses under D₁ is a subset of
    those under D₂.
    
    This means more restrictive strategies cannot create new jailbreaks,
    only potentially eliminate them. -/
theorem jailbreak_set_monotone {V : Type*} [Fintype V] [DecidableEq V]
    (M : Model V) (D₁ D₂ : DecodingStrategy V) (p : Prompt V) (n_max : ℕ)
    (hmore : isMoreRestrictive D₁ D₂ M) :
    {r : Response V | r.length ≤ n_max ∧ Judge p r = true ∧ isReachable M D₁ p r} ⊆
    {r : Response V | r.length ≤ n_max ∧ Judge p r = true ∧ isReachable M D₂ p r} := by
  intro r ⟨hlen, hjudge, hreach⟩
  exact ⟨hlen, hjudge, reachability_monotone M D₁ D₂ p hmore r hreach⟩

/-! ## Theorem 4: Binary Search Correctness -/

/-- **Theorem 4a (Sandwich property)**: If UNSAT at ε_high and SAT at ε_low,
    then the true safety bound lies in [ε_low, ε_high].
    
    More precisely: there exists a jailbreak with probability ≥ ε_low threshold,
    but no jailbreak with probability ≥ ε_high threshold. -/
theorem binary_search_sandwich {V : Type*} [Fintype V] [DecidableEq V]
    (M : Model V) (p : Prompt V) (D : DecodingStrategy V)
    (ε_low ε_high : ℝ) (hε_low : 0 < ε_low) (hε_high : 0 ≤ ε_low)
    (horder : ε_low < ε_high)
    (hsat : jailbreakOracleProblem M p D ε_low)
    (hunsat : ¬jailbreakOracleProblem M p D ε_high) :
    ∃ r : Response V,
      Judge p r = true ∧
      responseProb M D p r ≥ jailbreakThreshold M p D ε_low r.length ∧
      responseProb M D p r < jailbreakThreshold M p D ε_high r.length := by
  obtain ⟨r, hprob, hjudge⟩ := hsat
  refine ⟨r, hjudge, hprob, ?_⟩
  have := unsat_implies_safety_bound M p D ε_high r.length hunsat r (by omega)
  rcases this with h | h
  · exact h
  · simp [hjudge] at h

/-- **Theorem 4b (Interval halving)**: Each binary search iteration halves the
    uncertainty interval.
    
    If we probe at ε_mid = (ε_low + ε_high) / 2, then we can update either
    ε_low or ε_high, cutting the search interval in half. -/
theorem binary_search_halves {V : Type*} [Fintype V] [DecidableEq V]
    (M : Model V) (p : Prompt V) (D : DecodingStrategy V)
    (ε_low ε_high : ℝ) (horder : ε_low < ε_high) :
    let ε_mid := (ε_low + ε_high) / 2
    ε_low < ε_mid ∧ ε_mid < ε_high := by
  constructor <;> linarith

/-- **Theorem 4c (Convergence)**: Binary search converges to the critical threshold.
    
    After n iterations, the uncertainty interval has width at most
    (ε_high - ε_low) / 2^n, which approaches 0 as n → ∞.
    
    This guarantees we can approximate the safety radius to arbitrary precision. -/
theorem binary_search_converges (ε_low ε_high : ℝ) (horder : ε_low < ε_high) :
    ∀ n : ℕ, ∃ ε_low' ε_high' : ℝ,
      ε_low ≤ ε_low' ∧ ε_low' < ε_high' ∧ ε_high' ≤ ε_high ∧
      ε_high' - ε_low' ≤ (ε_high - ε_low) / (2 : ℝ) ^ n := by
  intro n
  induction n with
  | zero =>
    refine ⟨ε_low, ε_high, le_refl _, horder, le_refl _, ?_⟩
    simp [pow_zero, div_one]
  | succ n ih =>
    obtain ⟨ε_low', ε_high', hlow, hord, hhigh, hwidth⟩ := ih
    let ε_mid := (ε_low' + ε_high') / 2
    refine ⟨ε_low', ε_mid, hlow, ?_, ?_, ?_⟩
    · show ε_low' < (ε_low' + ε_high') / 2
      linarith
    · calc ε_mid
          = (ε_low' + ε_high') / 2 := rfl
        _ ≤ (ε_high + ε_high) / 2 := by linarith
        _ = ε_high := by ring
    · have : ε_mid - ε_low' = (ε_high' - ε_low') / 2 := by field_simp; ring
      rw [this]
      calc (ε_high' - ε_low') / 2
          ≤ ((ε_high - ε_low) / (2 : ℝ) ^ n) / 2 := by
            apply div_le_div_of_nonneg_right hwidth
            norm_num
        _ = (ε_high - ε_low) / (2 : ℝ) ^ (n + 1) := by rw [pow_succ]; ring

/-! ## Additional Properties -/

/-- The safety radius is bounded above by 1, since all response probabilities
    are at most 1. -/
theorem safetyRadius_le_one {V : Type*} [Fintype V] [DecidableEq V]
    (M : Model V) (D : DecodingStrategy V) (p : Prompt V) (n_max : ℕ) :
    safetyRadius M D p n_max ≤ 1 := by
  unfold safetyRadius
  by_cases h : ∃ r : Response V, r.length ≤ n_max ∧ Judge p r = true
  · apply csSup_le
    · obtain ⟨r, hlen, hjudge⟩ := h
      use responseProb M D p r, r, ⟨hlen, hjudge⟩
    · intro b hb
      obtain ⟨r, _, rfl⟩ : ∃ r ∈ {r : Response V | r.length ≤ n_max ∧ Judge p r = true}, responseProb M D p r = b := hb
      -- responseProb is at most 1
      calc responseProb M D p r
          ≤ responseProb M D p [] := prefix_prob_ge M D p r 0 (Nat.zero_le _)
        _ = 1 := by unfold responseProb; simp
  · push_neg at h
    have : responseProb M D p '' {r : Response V | r.length ≤ n_max ∧ Judge p r = true} = ∅ := by
      ext x
      simp only [Set.mem_image, Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
      intro ⟨r, ⟨hlen, hjudge⟩, _⟩
      exact h r hlen hjudge
    simp [this, Real.sSup_empty]

/-- The safety radius is nonnegative (since it's a supremum of nonnegative values). -/
theorem safetyRadius_nonneg {V : Type*} [Fintype V] [DecidableEq V]
    (M : Model V) (D : DecodingStrategy V) (p : Prompt V) (n_max : ℕ) :
    0 ≤ safetyRadius M D p n_max := by
  unfold safetyRadius
  by_cases h : ∃ r : Response V, r.length ≤ n_max ∧ Judge p r = true
  · obtain ⟨r, hlen, hjudge⟩ := h
    have hbound : BddAbove (responseProb M D p '' {r : Response V | r.length ≤ n_max ∧ Judge p r = true}) := by
      use 1
      intro b hb
      obtain ⟨r', _, rfl⟩ : ∃ r' ∈ {r : Response V | r.length ≤ n_max ∧ Judge p r = true}, responseProb M D p r' = b := hb
      calc responseProb M D p r'
          ≤ responseProb M D p [] := prefix_prob_ge M D p r' 0 (Nat.zero_le _)
        _ = 1 := by unfold responseProb; simp
    have hmem : responseProb M D p r ∈ responseProb M D p '' {r : Response V | r.length ≤ n_max ∧ Judge p r = true} := by
      use r, ⟨hlen, hjudge⟩
    calc 0
        ≤ responseProb M D p r := responseProb_nonneg M D p r
      _ ≤ sSup (responseProb M D p '' {r : Response V | r.length ≤ n_max ∧ Judge p r = true}) :=
          le_csSup hbound hmem
  · push_neg at h
    have : responseProb M D p '' {r : Response V | r.length ≤ n_max ∧ Judge p r = true} = ∅ := by
      ext x
      simp only [Set.mem_image, Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
      intro ⟨r, ⟨hlen, hjudge⟩, _⟩
      exact h r hlen hjudge
    simp [this, Real.sSup_empty]

/-- If a jailbreak exists at probability p, then the safety radius is at least p. -/
theorem safetyRadius_ge_of_jailbreak {V : Type*} [Fintype V] [DecidableEq V]
    (M : Model V) (D : DecodingStrategy V) (p : Prompt V) (n_max : ℕ)
    (r : Response V) (hlen : r.length ≤ n_max) (hjudge : Judge p r = true) :
    safetyRadius M D p n_max ≥ responseProb M D p r := by
  unfold safetyRadius
  apply le_csSup
  · use 1
    intro b hb
    obtain ⟨r', _, rfl⟩ : ∃ r' ∈ {r : Response V | r.length ≤ n_max ∧ Judge p r = true}, responseProb M D p r' = b := hb
    calc responseProb M D p r'
        ≤ responseProb M D p [] := prefix_prob_ge M D p r' 0 (Nat.zero_le _)
      _ = 1 := by unfold responseProb; simp
  · use r, ⟨hlen, hjudge⟩

/-- If no jailbreak exists (within length bound), the safety radius is 0. -/
theorem safetyRadius_eq_zero_of_no_jailbreak {V : Type*} [Fintype V] [DecidableEq V]
    (M : Model V) (D : DecodingStrategy V) (p : Prompt V) (n_max : ℕ)
    (hno : ∀ r : Response V, r.length ≤ n_max → Judge p r = false) :
    safetyRadius M D p n_max = 0 := by
  unfold safetyRadius
  have : responseProb M D p '' {r : Response V | r.length ≤ n_max ∧ Judge p r = true} = ∅ := by
    ext x
    simp only [Set.mem_image, Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
    intro ⟨r, ⟨hlen, hjudge⟩, _⟩
    have hfalse := hno r hlen
    rw [hfalse] at hjudge
    exact Bool.false_ne_true hjudge
  simp [this, Real.sSup_empty]
